//: Playground - noun: a place where people can play

import UIKit

// https://www.hackerrank.com/challenges/hackerrank-in-a-string/problem

let ab = "bvxqokorcxbivcnvdmcametgxvzftjkiyzatzatnapwttpxwqegvxllbtvxfnmwwbkicnaxmjxwgecexnndlgmwfsiusksumczuzfpajpmsboatncwzecbkxavloimnkllziuvaikvogykbcqizbqmdxyipclavzgvgonstdzpzskwvixgdfyblmmymtxwoxsoyqlqzbsyuatyebgkwznlnxqjefgkeluqcvtgmtvjsbaalxpqdmkptbqyefleiulcbsijglnawbwmbzuqybuqfmpewqnvnxqpawngtmuplfvlctyysbicubvnbjaayepapsotfzzfpdifsnpovufuuxsevipbbylkyoboqjatntvtqpbxjgposuleiqjnzbdecuzdjujweuztnwoggaoljoniwpkdbttjpnfomegodafcqpfjoxcpaiejdnnkvavjxgnbffuzkaozveqekvmdvwfnldlpzbkyioczsqnggspqgeyktlksupywxkgydwzovlndectcjwnxikuwcqdapqlvsdlboaesypkpujcdmwqmvfoqlsptkkzwsmauadiuqoygoucdzcgoodmdmwcaafwygzktolpqzvyovekgpobndncyzmpemzsxtzovjxzettonibczyyxdfvbealnzsoysminakkcwlmnnxnlultsnagfllmckenvbyimcmxsxkwfxcozjniayaydmausxgwntoxplvmnbqmgnbqibbksgxzjydswmdlmxdcjzszicsowtnntakaopldgywibqdbiapexeumwizozfdjzdjfevwkycctuoplypfvnlclilayfgntuaidctvxntujlaqzizoiueqgkydnzqfeaizobbniyswfaooxuzxfcuvsplksvgqnpitctdkymlytpxtzikveznmvzakpiecagzilefzluzfxexzwiwcfmwfgbvumcalixagmikxgdwjdblzlowyximkgwtwgkcycluaiuddfocelymvfccfbwykfobxpuwxkbppsgyndquubdvtmzjfeoiddeydndzpciidysilvtmtfjiejaodwakwbmqgcgklvljfykmglvikblmdyynxuigxgkujcjtenjgpdimocywaxfwqusyzpytwxpvsbxqqqjbcvzqfmppaixnofygmxilxijxzyxgmfjiosgxasfbnanzqawmiuzdpbygzussrymjsbdjwsxzxxpjzskoqqslqwxlnvqycqtmsklyywuqfdkfofwtoeccajywebpwwxydjvqcdgaaztmxntemvlqxpsstzlzullnpxbyjywstjelfjeizvzjfguimgoacptxioauqiqkabptbsebcdzctdtyqapbjastgmlvoekosvkfbzfbnwkoiytspdkeoywpaajkqvlgvjqqgdomywcsgojgkiewjcytaskqgloqtdjbssfjdcgxmjtsbmmgkbdakxclflnmadmbnzljqqunuwwvvquxjtiiazivxoogvbmpajvbtclkjjyjovbstpvgspigyctgcbxxockkvlzllftwzbnlpnjxoppkluqoxkpaauipgndpixfeqyucgtyqfngemdnyfywiyafxtcfypgcvslwmzxtmxqljdcxibsfctqsgipwqjcvkcziwjeyzkjocynfmbwmokmkbitlxceucgksjytasldlngbvzegokdppywngxululnxvxcuiffgiyzjbfqfkfdnqwtmaknebokdistbgvunmdfdplxfosoixqcaalexpnvffaxtzmdafsczxbtwejnabxiugiecdjvjaduyswnqmgogjsnqajqjvekonsfamdiblvwidimdkblpbzcubdieztmmyibdzaoljbaiptpvqaofgnxcuwmycdqijtwonoivfxjdayagywnazkzgmlcdwcjvssyjndebotuybwkffvazpbcddkgoqjtqtpxljosfcsebmoyajqagcfpngmjfcsjgnzcmlftngnococzvnybagwdfgmnvlcsuyxniomxqcmaebfadlopzcznepbixvkxxvvsajitzxcvvbezmbnglkwsnmqxecgfjxcvzsysokyewupakmfjjtwjiqwexitgoznwtimxzgewskdmicmgmpoekeypqusfitatpfovzlgkgxizbntbjqpcafpzuwocpkyjguoqmcnpeivbdqldcqkawikuvkmdbqvaikitakpyfvgacxtiijcvjijaowtmixlcoocdwgkeajvyfktgjwzzanxclapampbxgbmtetngyyumkemiqiggfxvoubsiemjwfyjzwlsxqfpotdbpusluexmuwkyzqsjlsloldiqyjblpsujxtfeeixluktalimfdiiwubqvdsmbbjxzcvdqtgbtevmlkolmnsiydxuaaubulnzscoopuqakwnnwgnvpignakbpwkgapuwuawdmdactluoovbbotgbafszbgukovsdnknakzyczlzqvqmeenpiyywcioanbbqffscplmntvaspeqaqmlxjywonjenoozpqebjliftfmlbeymayspcyllcetbtmoidbmwdonfnuxpttqbaoeiweykwtuakmajwlzuymbbcxcnnxezkzypyqaufbxziyfyggsfkjyjzlqqxnuypvimvwbbxwlavxjninvxjyddejclcaodwfucdsmkccvaoynvsficxzdnmyvfbdotsmncicjnsiqafizvibgqeapntkniagampbckuuezbnydoplvgjejqtilxajfqkkpxcdpyqbeiisucqybscyscscpaaqyvgmcmcijtwmkiaozeluxvukxbmizpxndyjxsuiaizawtxwoqjpugizvufwjvxscoeiqzdcqmcisckkskpzovfeukzdamjilzedgpbnddstwoblwevduslwgxqvttjesioswkfgojkmdzgytvuugewesjgquvcdkuokzieaizeenqdazmeobcofxgldvkxqiewulyaqzxejbkpayjcywmaeuoxfgtdymvenxmfiqbvdzissqampwpooovsoiflpoqydauotdkqjefzqtuogaftyjmpuuxkqgkaczwisyctlbqzsjusmapxtsyucsjzswbfcnqgzeasffawejjmvkaofoigkxzawcbfwvfejndvtokcljtdbsuieiqjnbesgbsjvslinnankqdobkkszaeknuddvuvgggdcyezlogexcpeqxuowjiwzvbliiymtbdlkltsimlxnaunaywzgjczuymtwtekdcnjwadoxcbfjdqmdnevjglqmamkdmabmmpigwtkgexknzqjdbtgvbzddvxvqqemnutoolglfjpkiuusilpqstsgvomtbgzcngfcjcdvviafqstxulqxqtwiulbmnqbfbvwsbkrgcmoifvfbtwfwjgsvaokzbicqxgpjopgyasxtcpyfylvodvtvfgsefulctkvwwyvlyngblgbbsnimeduwtsljfivqstkucdsgtwfpmdpeysogolimyquyaqegdgzmtecdjvkoudddglgloknwetevoylfmuyzlyzmbnmidwqfjzfvqfsnyujzvowbeaaxwexxoxbbacbxwjmxycocsjeywkinejdzvqoqwuygaibgtqjgfcntykovlnpgkexaegtgtkbdnqybbyxyuolewqzmiygtgjjydkdwzuobxnmsyfvknpxtpjliokwiubfdmdyzuwwcbovzzzzvinosvytlkospmtoffymqqxpfvlgzuwvbpkxmtkoulfqtepxnymktekecsbcjjepfkfymtknlsimdskbqblggvdsjmbeddyfqgydjocitgyaxfetweuqgddjblftvntcvsyfiaocolgwzcwnaxjmknejyfqbcmnpxobbometbyxndxxvxoiizxtdtwziwnaytyjdibyiknunywxabvoobxvdqvdwefywecgcqtcdjwelycezpvepjqosglnwpmmvzkbeifdzwgjytespluszuwvqdtfxldyaqudvfeuybfyjvxsxsedmppkmgcpbgjlsqzsmijmnzawagoiegjjvacxbczbyauuntdyqabsfgdoxptqxlpdgkunovezpaadvynncqdsdxxjnzqyfluujkjemxnxqpklbnzluaxwjubjmfvnkfwsxefmvabfeuvnfzioulufpzanmkkdbnvuelxugxngbezvyqcibeiudkvieaklzddeugnypwfebgpzxoqbpwoxwtmdvjfzvwncdosekzffuifkjyakdjpuypsdkvkgasqffxzqkmpmuejxgwcoppuidbgecndopibdotpdxkslywmcfaetmsxdkwypybggasmlwqjmvnlbivxketutvxpwvgbzfgpmsvcvvtwkloeljxalxzzfgbbcllopakazjvzgqadvllywpxamyodlvvqmpqgfbmcalnmzkqznflwvfzzaxdoyeczavqwpxuxglulkeaqumbdyzoutwtkbneoxlqlkleeotwtydzdcqipgyfdecjpyfvgzzmekmtlisyaldogvpwcqjdsgwucptuaibvntpukmgvjjansjkmpylvexmqgysjnwqnwudoqoquflcqyzffewolymmosbxvcgbnaauxopkllslgeguzngxszbkbdvfnvaitxtaimctciiydovnnffaamfvtawoqazqkdnpwuxkvxfapbogupbfoguzdivsxuyvdgyvwkcvkoptkdiunguslfafuoixcvwgxauqjnpfimlkavqpdomyiefhoisfujicsxglubqntfamsndkvgviukzfoxipwgtuewjpnzpllfmsilwgbvoajuydsnjollmljygoqfjujazlgxdwbwoiywlejidwjigiftnnbfnxzqvqyempksflipedanfpxknvmzezpfytiwwoadjfibznntgwtwwkkvqvdoqpysbfmbzkcxiwqftcgpwobcsefynfsxmsjmnlspimoftwcxkmzvudzgydagjajfdvnlgsybafzmccsykpjpvuekxkgkcfdniecdoquugwegimkdioekyubebqlwwuszbiynpwffeybuuiomwwsdppdneuunjgxktscgzzyqgwlesywoibkfidnogmgbtasxleelkxtecwssjusbcptnggtvxpincqvujktpzhm"

var source = [[String]]()
var find: [String] = ["h", "a", "c", "k", "e", "r", "r", "a", "n", "k"]

for i in 0..<1 {
    var arr = ab.characters.map({ (c: Character) -> String in
        let s = String(c)
        return s
    })
    source.append(arr)
}

for i in 0..<source.count {
    var isValid = "YES"
    
    if find.count > source[i].count {
        print("NO")
        continue
    }
    
    for value in find.enumerated() {
        if let index = source[i].index(of: value.element) {
            source[i].remove(at: index)
        } else {
            isValid = "NO"
            break
        }
    }
    
    print(isValid)
}